### ISSUE TITLE
Suggest NodeJS TLS Connection Reuse in AWS SDK

### ISSUE THREAD

**Issue by Artiavis** [Aleksandr-Filichkin/aws-lambda-runtimes-performance#7]
Nice to see others profiling runtimes.

I ran into this issue with AWS Lambdas written in NodeJS being bizarrely slow a while back. It’s a legacy issue with how the AWS SDK for JavaScript works. If you have time, I suggest you try again with this one simple fix. I think you’ll be impressed.

https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/node-reusing-connections.html

**Comment by Aleksandr-Filichkin** [comment]
Done
https://github.com/Aleksandr-Filichkin/aws-lambda-runtimes-performance/blob/main/template-final.yaml#L265
